# Generated by Django 3.1.1 on 2020-09-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200905_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relased',
            new_name='released',
        ),
    ]
