# Generated by Django 3.1.1 on 2020-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200906_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(1, 7), (2, 13), (3, 16), (4, 18)], null=True),
        ),
    ]
