# Generated by Django 3.1.1 on 2020-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(7, 7), (13, 13), (16, 16), (18, 18)], null=True),
        ),
    ]
