# Generated by Django 3.1.1 on 2020-09-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200906_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country']},
        ),
    ]
