# Generated by Django 3.1.1 on 2020-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200906_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
